cardano-foundation/cardano-rosetta

cardano-rosetta-server/src/server/controllers/network-controller.ts, cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
This PR updates the cardano-node version that is hardcoded on /network/options
`yarn test`
=> feat: update cardano node version

.github/workflows/ci.yml, cardano-rosetta-server/src/server/controllers/controllers.ts, cardano-rosetta-server/src/server/controllers/network-controller.ts, cardano-rosetta-server/src/server/index.ts, cardano-rosetta-server/src/server/server.ts, cardano-rosetta-server/src/server/utils/cardano-node.ts, cardano-rosetta-server/src/types/app.d.ts, cardano-rosetta-server/test/e2e/network/network-options-api.test.ts, cardano-rosetta-server/test/e2e/utils/test-utils.ts
This PR adds query to cardano-node for node version
`yarn test`
**Remember to add to .env file and .env.test CARDANO_NODE_PATH to its corresponding cardano-node path**
=> feat: added query to cardano-node for node version

nix/cardano-rosetta-server.nix, nix/nixos/cardano-rosetta-server-service.nix, nix/nixos/default.nix, nix/nixos/module-list.nix, release.nix
Adds a Nix server service for `cardano-rosetta-server`.
=> [SRE-127] Add Server Service

cardano-rosetta-server/src/server/db/network-repository.ts
This PR improves coverage test on network-repository
Remove unused function call
`yarn test`
=> chore: remove unused function

cardano-rosetta-server/src/server/controllers/block-controller.ts, cardano-rosetta-server/src/server/controllers/controllers.ts, cardano-rosetta-server/src/server/db/blockchain-repository.ts, cardano-rosetta-server/src/server/db/network-repository.ts, cardano-rosetta-server/src/server/db/queries/network-queries.ts, cardano-rosetta-server/src/server/services/cardano-services.ts, cardano-rosetta-server/src/server/services/services.ts, cardano-rosetta-server/test/e2e/construction/construction-combine-api.test.ts, cardano-rosetta-server/test/e2e/construction/construction-derive-api.test.ts, cardano-rosetta-server/test/e2e/construction/construction-submit-api.test.ts, cardano-rosetta-server/test/e2e/construction/cosntruction-payloads-api.test.ts, cardano-rosetta-server/test/e2e/environment-parser.test.ts, cardano-rosetta-server/test/e2e/fixture-data.ts, cardano-rosetta-server/test/e2e/network/netowork-status-api.test.ts, cardano-rosetta-server/test/e2e/network/network-list-api.test.ts, cardano-rosetta-server/test/e2e/network/network-options-api.test.ts, cardano-rosetta-server/test/e2e/server/server.test.ts
Fixed all linter warnings
n/a
n/a
`yarn lint`
=> chore: fixed all linter warnings

CHANGELOG.md, README.md, cardano-rosetta-server/docker-compose.yml, cardano-rosetta-server/package.json
=> release/ 1.0.0

test/check/.gitignore, test/check/README.md, test/check/configuration/construction/configuration.json
We're currently lagging behind the `rosetta-cli` releases and our config is now incompatible with the latest version [`rosetta-cli@0.6.2`](https://github.com/coinbase/rosetta-cli/releases/tag/v0.6.2)
Update configuration and version requirements
```
Success: Index End Condition [Index: 10000]
+--------------------+--------------------------------+--------+
|  CHECK:DATA TESTS  |          DESCRIPTION           | STATUS |
+--------------------+--------------------------------+--------+
| Request/Response   | Rosetta implementation         | PASSED |
|                    | serviced all requests          |        |
+--------------------+--------------------------------+--------+
| Response Assertion | All responses are correctly    | PASSED |
|                    | formatted …
```
=> chore: update check configuration for rosetta-cli@0.6.2

cardano-rosetta-server/src/server/index.ts, cardano-rosetta-server/src/server/services/network-service.ts, cardano-rosetta-server/src/server/services/services.ts, cardano-rosetta-server/src/server/utils/constants.ts, cardano-rosetta-server/test/e2e/utils/test-utils.ts, cardano-rosetta-server/test/unit/services/netowork-service.test.ts
Closes: #238
As stated in #238 
n/a
n/a
=> fix: networkId is now taken from the network magic

cardano-rosetta-server/src/server/controllers/account-controller.ts, cardano-rosetta-server/src/server/controllers/block-controller.ts, cardano-rosetta-server/src/server/controllers/construction-controller.ts, cardano-rosetta-server/src/server/controllers/controllers-helper.ts, cardano-rosetta-server/src/server/controllers/controllers.ts, cardano-rosetta-server/src/server/controllers/network-controller.ts, cardano-rosetta-server/test/e2e/block/block-api.test.ts, cardano-rosetta-server/test/unit/services/netowork-service.test.ts
An error was introduced when fixing #238 
The issue was fixed and more tests were added
N/A
As usual
=> fix: networkId wasn't properly checked after #238

README.md, cardano-rosetta-server/README.md, docs/rosetta-custom-definitions.md, docs/staking-support.md, examples/README.md
This PR introduces some improvements to document customizations introduced into Rosetta Spec
I cretated a documentn in `/docs` although it might not be the best option. @rhyslbw it would be great to get your input about this.
n/a
n/a
=> chore: 14 -  finalize documentation

cardano-rosetta-server/src/server/services/cardano-services.ts, cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
This PR increases the test coverage.
- Adds more tests for the `construction/payloads` endpoint.
- Removes unreachable code in `cardano-service`.
=> test: coverage increase for cardano service related endpoints

config/network/shelley_qa/cardano-db-sync/config.json, config/network/shelley_qa/cardano-db-sync/pgpass, config/network/shelley_qa/cardano-node/config.json, config/network/shelley_qa/cardano-node/topology.json, config/network/shelley_qa/genesis/byron.json, config/network/shelley_qa/genesis/shelley.json
=> Chore/Add shelley_qa network config

cardano-rosetta-server/src/server/db/blockchain-repository.ts
Little refactor to bring all operations data at `/block` and `/block/transactions` endpoints
=> Feat: refact populateTransactions at blockchain-repository

cardano-rosetta-server/README.md
This PR introduces a description about e2e tests snapshot generation
=> docs: tests snapshot generation explanation

examples/package.json, examples/withdrawal-example.ts
Now withdrawal script example should work with the correct values.
=> Fix: withdrawal example

examples/README.md
Update `/examples/README.md` in order to newly added script withdrawals.
=> docs: update examples readme for withdrawals

config/network/launchpad/cardano-db-sync/config.json, config/network/launchpad/cardano-db-sync/pgpass, config/network/launchpad/cardano-node/config.json, config/network/launchpad/cardano-node/topology.json, config/network/launchpad/genesis/byron.json, config/network/launchpad/genesis/shelley.json
The public testnet `launchpad` contains MA activity.
Add the config, to be build using the build arg,
=> chore: add launchpad network config

cardano-rosetta-server/src/server/openApi.json, cardano-rosetta-server/src/types/rosetta-types.d.ts
This PR updates the schema in order to add MultiAssets supoort
Api has changed although it should not break anything
n/a
=> feat: added multiassets representation to the openapi.json definition

cardano-rosetta-server/src/server/db/blockchain-repository.ts, cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts, cardano-rosetta-server/src/server/models.ts, cardano-rosetta-server/src/server/utils/data-mapper.ts, cardano-rosetta-server/test/e2e/block/block-api.test.ts, cardano-rosetta-server/test/e2e/block/block-transactions-api.test.ts, cardano-rosetta-server/test/e2e/fixture-data.ts
Add token bundles to transaction operations (input and output)
=> feat: add token bundle to transaction operations

cardano-rosetta-server/src/server/utils/cardano/cli/cardanonode-cli.ts
Closes #273 
Just removed an unused parameter
n/a
Running the send transaction workflow
=> refactor: removed --shelley command from node-cli tx submission

test/check/README.md, test/check/configuration/construction/transfer-ma.json, test/check/configuration/construction/transfer-multiple-ma.json, test/check/workflows/transfer-ma.ros, test/check/workflows/transfer-multiple-ma.ros
This PR implements #274 
Checkout the `README`
N/A
Steps are explained in the `README`
=> feat: rosetta-cli check:construction MA workflow

test/check/README.md
Fix transfer-multiple-ma.json example command.
N/A
N/A
N/A
=> Update check README.md

release.nix
=> Fix hydra release.nix ci

README.md
Change version in main readme to 1.1.0 inline with latest release tag.
N/A
N/A
N/A
=> Change version in readme from 1.0.0 to 1.1.0

docs/multi-assets-support.md
Add `/account/balance` response example to docs/multi-assets-support.md
N/A
N/A
N/A
=> Fix: Add account balance response example to doc

cardano-rosetta-server/README.md, cardano-rosetta-server/config/exemptions.json, cardano-rosetta-server/src/server/controllers/network-controller.ts, cardano-rosetta-server/src/server/services/network-service.ts, cardano-rosetta-server/src/server/utils/data-mapper.ts, cardano-rosetta-server/src/types/app.d.ts, cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
Exemption types information was added in the network options response. 
A new service method was added in the network-service that retrieves exemption types.
- Modify network controller test
=> feat: adding exemption types to network options endpoint

cardano-rosetta-server/src/server/controllers/construction-controller.ts, cardano-rosetta-server/src/server/controllers/controllers.ts, cardano-rosetta-server/src/server/controllers/network-controller.ts, cardano-rosetta-server/src/server/db/blockchain-repository.ts, cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts, cardano-rosetta-server/src/server/index.ts, cardano-rosetta-server/src/server/services/block-service.ts, cardano-rosetta-server/src/server/services/cardano-services.ts, cardano-rosetta-server/src/server/services/network-service.ts, cardano-rosetta-server/src/server/services/services.ts, cardano-rosetta-server/test/e2e/construction/construction-metadata-api.test.ts, cardano-rosetta-server/test/e2e/fixture-data.ts, cardano-rosetta-server/test/e2e/utils/test-utils.ts, cardano-rosetta-server/test/unit/services/cardano-services.test.ts
Modified minFeeA and minFeeB sources. Got them from database.
=> feat: changed minFeeA and minFeeB sources. Got them from database

examples/commons.ts, examples/delegate-stake-example.ts, examples/ma-transfer-example.ts, examples/send-transaction-example.ts, examples/withdrawal-example.ts
Since the API was upgraded to v1.4.10 some of the scripts on the examples folder got deprecated. Adaptations to them are introduced in this PR.
=> fix: fix examples tests

cardano-rosetta-server/src/server/server.ts, cardano-rosetta-server/src/types/app.d.ts
A bug ocurred when a body limit variable was set.
Casting the variable to number.
No tests were changed.
=> fix: body limit fixed from environment variables

docs/pool-operations-support.md
Adds support documentation for stake pool operations.
A new document describing the solution.
No tests were modified.
=> feat: pool retirement documentation support

cardano-rosetta-server/src/server/services/cardano-services.ts, cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts, cardano-rosetta-server/src/server/utils/data-mapper.ts, cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts, cardano-rosetta-server/test/e2e/fixture-data.ts
Fees for pool retirement operations were not properly calculated since the pool refund deposit should not exist
=> Fix fees calculation when making pool retirement

test/check/README.md, test/check/configuration/construction/pool-registration-configuration.json, test/check/workflows/pool-registration.ros
Adds Rosetta cli workflow for pool registration operations
=> test: add pool registration workflow

test/check/configuration/construction/pool-registration-cert-configuration.json, test/check/workflows/pool-registration-with-cert.ros
Adds workflow and documentation for sending a tx with `pool registration with cert` operation
=> test: add workflow for pool registration with cert

test/check/README.md, test/check/configuration/construction/pool-registration-cert-configuration.json, test/check/workflows/pool-registration-with-cert.ros
Adds documentation for pool with cert workflow
=> Add doc for pool registration with cert workflow

test/check/README.md, test/check/configuration/construction/pool-registration-cert-configuration.json, test/check/workflows/pool-registration.ros
Fixes port and relative path for pool registration with cert configuration file, and fixes  pool registration workflow.
=> test: fix configuration files for rosetta tests

test/check/README.md, test/check/configuration/construction/pool-retirement-configuration.json
Fix check test readme for staking retirement scenario and corrects the location of retirement workflow.
_**Optional** Explain how does this PR solves the problem stated in [Description](#Description). You can also enumerate different alternatives considered while approaching this task._
_**Optional** Notice Reviewers about changes that were introduced while developing this task_
_**Optional** Leave some recommendations should be useful while reviewers are testing this PR_
=> Fix test check readme and pool-retirement-configuration.json

examples/README.md, examples/package.json, examples/send-transaction-using-cardano-address-example.ts, examples/yarn.lock
This example shows how to create and send a transaction and it is compatible with [cardano-addresses](https://github.com/input-output-hk/cardano-addresses) `Ed25519-bip32` standard. 
See https://github.com/input-output-hk/cardano-rosetta/issues/331#issuecomment-848062182 for further details.
Emurgo serialization lib was used in order to derive and sign the transaction. It's important to mention that *key generation and the signing process is pushed to the clients by Rosetta design*. This could have been implemented using any other library or even language. `Ed25519-bip32` is not part of Rosetta scope.
n/a
Running the following `cardano-address` commands shoild result in the same addresses and keys than running this script:
```bash
echo "gasp below arrange frown canvas heart pet hole lunar …
```
=> docs: added an example that's compatible with cardano-addresses tool

cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts, cardano-rosetta-server/test/e2e/fixture-data.ts
Add sort to transaction outputs query in order to retrieve outputs by index
Run test suite
=> Fix transaction with withdrawal test

cardano-rosetta-server/src/server/utils/cardano/cli/cardanonode-cli.ts
Allows submitting a tx of Alonzo era.
Depends on #403
=> Submit Alonzo tx

examples/commons.ts, examples/ma-transfer-example.ts
Small fix to `send transaction with` ma example
=> Fix ma-transfer example

test/check/README.md, test/check/configuration/construction/vote-registration-configuration.json, test/check/workflows/vote-registration.ros
Adds check construction workflow to register a Catalyst vote.
Depends on ##417
=> test: check vote registration for rosetta cli

docs/catalyst-vote.support.md, docs/pool-operations-support.md, docs/rosetta-custom-definitions.md
Adds documentation on how Rosetta traits vote registration operations.
=> Add documentation for vote registration

cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
Querying for UTXO or balances at a specific block was taking too much time. This commit improves the way failed transactions are filtered in order relying upon the tx already being queried
Not to query for all the valid transactions when filtering
Changed how balance and utxos are fetched
- executing `check:data` on mainnet would suffice as it was failing for @rhyslbw 
```
./bin/rosetta-cli check:data --configuration-file ./configuration/data/shelley_sample.json
./bin/rosetta-cli check:data --configuration-file ./configuration/data/shelley_transition.json
```  
- once the node is synced, query for:
- address: `DdzFFzCqrhsea2GLSJJUZoQzzZUiZLEgcHt8jgiEM8nWbZXpJQUuRCG2ZrZgFmLDaGijGkHm1mGZhsHSAFVgD3CJHQMJteo183cuHSLV`
- block: `404bf1e44885ec717ecf78600f583aed6de80c6f186c681c7bfcf4774ec09c5e`
=> perf: improves valid transaction filtering query

cardano-rosetta-server/README.md, cardano-rosetta-server/src/server/controllers/controllers.ts, cardano-rosetta-server/src/server/controllers/search-controller.ts, cardano-rosetta-server/src/server/db/blockchain-repository.ts, cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts, cardano-rosetta-server/src/server/db/queries/search-transactions-queries.ts, cardano-rosetta-server/src/server/index.ts, cardano-rosetta-server/src/server/models.ts, cardano-rosetta-server/src/server/server.ts, cardano-rosetta-server/src/server/services/block-service.ts, cardano-rosetta-server/src/server/services/cardano-services.ts, cardano-rosetta-server/src/server/utils/cardano/addresses.ts, cardano-rosetta-server/src/server/utils/constants.ts, cardano-rosetta-server/src/server/utils/data-mapper.ts, cardano-rosetta-server/src/server/utils/environment-parser.ts, cardano-rosetta-server/src/server/utils/errors.ts, cardano-rosetta-server/src/server/utils/formatters.ts, cardano-rosetta-server/src/server/utils/validations.ts, cardano-rosetta-server/test/e2e/account/account-balance-api.test.ts, cardano-rosetta-server/test/e2e/environment-parser.test.ts, cardano-rosetta-server/test/e2e/fixture-data.ts, cardano-rosetta-server/test/e2e/network/network-options-api.test.ts, cardano-rosetta-server/test/e2e/search/search-transactions-api.test.ts, cardano-rosetta-server/test/e2e/utils/test-utils.ts, docs/rosetta-custom-definitions.md
Adds rest of filters expected at `/search/transaction` endpoint
=> Add coin filter to search transactions

test/check/README.md, test/check/configuration/construction/pool-registration-cert-configuration.json, test/check/configuration/construction/transfer-multiple-ma.json, test/check/workflows/transfer-multiple-ma.ros
- c417d3aeac8ceee305381c0b685555dcde89df17
Update test/check README test cases
- 7cfe09a3bafe357ebe0167671e2fdcb561ae4133
Small fixes in workflows
- Update test/check README making (most of) tests stop using hard-coded values but rather generated data.
- Small fixes in workflows making them compatible with testnet.
=>  Update test/check README test cases

examples/postman/send_transaction.postman_collection.json
=> fix: postman tests

test/check/README.md
=> fix: updated test readme

Dockerfile, cardano-rosetta-server/docker-compose.yml
Bumps cardano-node to v1.35.3 & cardano-db-sync to v.13.0.4
=> chore: cardano-db-sync@13.0.4 & cardano-node@1.35.3

test/check/configuration/construction/configuration.json, test/check/configuration/construction/delegation-configuration.json, test/check/configuration/construction/pool-registration-cert-configuration.json, test/check/configuration/construction/pool-registration-configuration.json, test/check/configuration/construction/pool-retirement-configuration.json, test/check/configuration/construction/transfer-ma.json, test/check/configuration/construction/transfer-multiple-ma.json, test/check/configuration/construction/vote-registration-configuration.json, test/check/configuration/data/preview_sample.json, test/check/configuration/data/shelley_transition.json, test/check/workflows/delegation.ros, test/check/workflows/pool-registration-with-cert.ros, test/check/workflows/pool-registration.ros, test/check/workflows/pool-retirement.ros, test/check/workflows/transfer-ma.ros, test/check/workflows/transfer-multiple-ma.ros, test/check/workflows/transfer.ros, test/check/workflows/vote-registration.ros
Migrated all test configs from `testnet` to `preview` network
=> chore: updated test configs

cardano-rosetta-server/src/server/db/queries/search-transactions-queries.ts, cardano-rosetta-server/test/e2e/search/search-transactions-api.test.ts
Optimize search transaction queries. #481 Introduced complexity on some queries and made them take long periods of time to get executed.
Resolves #501
=> fix: optimize search transaction queries

Dockerfile, cardano-rosetta-server/docker-compose.yml
Updates:
- cabal@3.6.2.0
- cardano-node@1.35.4
- cardano-db-sync@13.1.0.0
=> chore: bump cardano service deps

CHANGELOG.md, Dockerfile, README.md, cardano-rosetta-server/docker-compose.yml, cardano-rosetta-server/package.json, cardano-rosetta-server/src/server/services/network-service.ts, cardano-rosetta-server/src/server/utils/errors.ts, cardano-rosetta-server/test/e2e/network/netowork-status-api.test.ts, cardano-rosetta-server/test/e2e/utils/topology-test.json, scripts/libblst.pc
Changed Dockerfile to build db-sync from source.
=> added building from source for db-sync
