cardano-foundation/cardano-rosetta

Dockerfile
README.md

The link to access the spec-compliant Dockerfile is invalid, and the version referenced needs to be updated to pick up the changes to the Ubuntu deps that was recently fixed. There was also an invalid path in the `rosetta-server-builder` stage, that has gone undetected until now due to the `dev.Dockerfile` not using it.
- Fixes the link
- Removes the `src` component of the invalid path
- Uses the master branch until the next release is made

fix: correct link to raw Dockerfile, use master until next release

---

Dockerfile
cardano-rosetta-server/README.md
cardano-rosetta-server/docker-compose.yml
config/ecosystem.config.js
dev.Dockerfile

Required ENVs are missing from the `cardano-rosetta-server` implementations in the Dockerfile:
- `DEFAULT_RELATIVE_TTL`
- `CARDANOCLI_PATH`
- `CARDANO_NODE_SOCKET_PATH`
It's also important to enable https://github.com/input-output-hk/cardano-rosetta/issues/28  
- Adds the ENVS Closes #145 
- Adds `cardano-node` to the `cardano-rosetta-server` Dockerfile stage Closes #28

Fix/set binary envs, add cardano-node

---

.github/actions/build_cardano_rosetta/action.yml
.github/workflows/update-data-cache.yml

To implement https://github.com/input-output-hk/cardano-rosetta/issues/129 in a timely manner, a Docker build cache and recent data cache must be maintained to limit sync time to a reasonable duration. Running an instance 24/7 just to keep the data volumes up to date is overkill, so the workload should be intermittent.  
- add Github Action to build Cardano Rosetta using cached build layers from a Docker Hub image.
- add workflow to run a Cardano Rosetta instance built from scratch using the cache, sync an S3 bucket containing a recent state, which is passes as a host mount
- after 1 minute shut down the instance and upload the new data.
- schedule to happen from the `master` branch` every hour
**N.B.** `rhyslbw/cardano-rosetta:master` is temporary until the `inputoutput` repository is …

ci: Add data cache update workflow for use in CI

---

cardano-rosetta-server/src/server/api-error.ts
cardano-rosetta-server/src/server/server.ts
cardano-rosetta-server/src/server/utils/errors.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
cardano-rosetta-server/test/e2e/server/server.test.ts

Without this change any non handled error would make the server crash as it was not returning a required by schema field.
- Improved error handling code in server
- Added some missing tests to verify everything works as expected
n/a
`yarn test`

fix: generic error handling

---

README.md
cardano-rosetta-server/README.md

The intention was to set a container name, but the command is wrong. Also some other improvements to be made
- Fix run command
- Add context to the volume name
- Add an estimated build time
- Format the links to make the MD file easier to manage

docs: correct --name argument and add context to volume name

---

README.md

- Corrects stated version to `1.4.1`
- Links to the versioned documentation
- Refers to Rosetta without "API", to align with how it is presented
- Drops `v` from the version name

Correct Rosetta reference in README

---

.github/workflows/nightly.yml

Until https://github.com/coinbase/rosetta-cli/issues/124 is addressed, it's best to keep this `check` disabled to avoid tarnishing the nightly test result.
- Revert 368b0bc56a9f41f97fa17861b59adede17908711 
- Add comment with link for context

Revert "Uncomment tests in nightly.yml (#161)", add context

---

.github/actions/build_cardano_rosetta/action.yml
.github/actions/smoke_test_cardano_rosetta/action.yml
.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/post_integration.yml
.github/workflows/post_release.yml
.github/workflows/pre_release.yml
docs/MAINTAINER.md

We require builds to be pushed to Docker Hub, to maintain a current build cache, and make pre-built images available as a convenience. We also need assurance prior to release that a fresh build completes, without using the cache.
- Adds three new Workflows:
- produce the `master` branch build for the build cache
- run and report results of a fresh build, then also build a testnet image using local cache
- post-release to deploy versioned images as a convenience
Smoke tests performed prior to pushing. 
Closes #126 Closes #127 Closes #140 
Automated testing is configured in the workflows, so testing will involve observing after the condition are triggered.

Docker Hub Continuous Deployment + Manual dispatched pre-release workflow

---

.github/workflows/nightly.yml
test/check/configuration/src/data/compat_patch.json

The last `rosetta-cli check:data` scenario was commented out of the Nightly due to a false negative, caused by a bug in the tooling. A new version was released, that fixes the issue. It was also not possible to manually trigger the workflow. 
- Update to `rosetta-cli@0.5.0` 
- Make it possible to trigger the Nightly workflow manually
https://github.com/coinbase/rosetta-cli/issues/127 requires a compatibility patch of `construction` config for the
`data` check to run.
If https://github.com/input-output-hk/cardano-rosetta/runs/1067293361?check_suite_focus=true passes we can merge this

ci: Updates to rosetta-cli v0.5.0

---

.github/workflows/post_release.yml

The non-critical [post-release workflow failed](https://github.com/input-output-hk/cardano-rosetta/actions/runs/238697742) due to an invalid Docker build context path. It's not possible to test locally due to a [limitation with act](https://github.com/nektos/act/issues/339)
Removes the invalid path component
Only another release will validate this fully, but we expect to have more before `1.0.0`

ci: fix build context in post-release workflow

---

cardano-rosetta-server/src/server/controllers/account-controller.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/test/unit/utils/data-mapper.test.ts

Coinbase team has reported that there was an error when executing `check:data`
```json
{
"error": "reconciliation failure: active reconciliation error for addr_test1vrd26p8d9dlknc4fhevzudcfzuul5qm2znquytugqcw583czzqrpm at 1630464 (computed: 37999999978288983ADA, live: 37999999978288984ADA)",
"end_condition": null,
"tests": {
"request_response": true,
"response_assertion": true,
"block_syncing": true,
"balance_tracking": true,
"reconciliation": false
},
"stats": {
"blocks": 4888313,
"orphans": 0,
"transactions": 60265,
"operations": 241741,
"active_reconciliations": 75757,
"inactive_reconciliations": 6219979,
"reconciliation_coverage": 0.007858546168958742
}
}
```
When calculating total balance, it was using a `Number` instead of a `BigInt`
n/a
`rosetta-cli check:data` for the blocks in …

fix: account total balance was calculated using Number instead of BigInt

---

cardano-rosetta-server/src/server/utils/environment-parser.ts

Socket seems not to be created when launching the app so it errors out
We just check it's a string now
n/a
n/a

fix: dont ask for socket file to exist when parsing env

---

.github/actions/smoke_test_cardano_rosetta/action.yml
.github/workflows/ci.yml
.github/workflows/post_integration.yml
.github/workflows/post_release.yml
.github/workflows/pre_release.yml
test/smoke_test.sh

Closes #180
- lift logic to bash script for portability
- check for readiness, retry every 3 seconds
- check for block index property existence
Automated - See result of this CI run [here](https://github.com/input-output-hk/cardano-rosetta/pull/181/checks?check_run_id=1100694743)

fix: strengthen Docker smoke test

---

README.md

Self-documenting
Provide a set of commands in a one-liner, to remove just the directory that forces the PostgreSQL rebuild. It stops and removes the `cardano-rosetta` container, then mounts and performs the `rm` in a self-removing `ubuntu` container.

docs: add postgres rebuild command to README

---

cardano-rosetta-server/src/server/services/cardano-services.ts
cardano-rosetta-server/test/e2e/construction/cosntruction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts

closes #184
Just filter duplicated addresses
n/a
Use the example project and send to transactions to the generated address before executing `yarn send-transactions-example` so it uses to inputs

fix: don't repeat witnesses if multiple inputs from the same address are used

---

Dockerfile

The spec suggested ubuntu:latest as a "good example", which at the point of
implementation, was a reference to `20.04` in the Docker Hub repository:
https://www.rosetta-api.org/docs/node_deployment.html#good-example-1
`20.04` is not a supported version for integration with the primary
consumer, so I have to infer `latest` at the time was pointing to `18.04`.
Change the base to `18.04` and all pinned dev dependencies

chore: downgrade Docker image base to Ubuntu 18.04

---

cardano-rosetta-server/src/server/controllers/network-controller.ts
cardano-rosetta-server/src/server/utils/constants.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts

We forgot to add the operation sin the proper `network` endpoint so `rosetta-cli` was complaining about it with the following error:
```bash
Error: unable to fetch block 4500003: Operation.Type is invalid: stakeKeyRegistration: operation type is invalid
```
Just added the operations as an array taken from the `enum` and now everything seems to be working just fine
n/a
- `rosetta-cli` where block `4500003` is contained (as it has a staking operation)

fix: there were missing some staking network operations

---

cardano-rosetta-server/test/e2e/construction/construction-metadata-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts
cardano-rosetta-server/test/unit/services/cardano-services.test.ts

- Adds the `minKeyDeposit` parameter that was missing in the cardano service unit tests (it wasn't used there since we don't include unit tests that need that value and, therefore the tests were passing but it was breaking the pipeline).
- Also fixed some linting warnings mainly in the e2e tests.

fix: missing parameter in cardano service linter fixes

---

README.md

The root README has the wrong version listed, as per https://github.com/input-output-hk/cardano-rosetta/blob/master/cardano-rosetta-server/src/server/openApi.json#L4

docs: correct Rosetta spec version

---

examples/commons.ts
examples/delegate-stake-example.ts

`delegate-stake-example` currently fails with error `'The transaction you are trying to build has more outputs than inputs'` due to not considering the 2 ada staking key registration fee. This was observed when funding the payment address with 10/15/25 ada.
This fix adjusts the output value so that 2 ada is reserved for this staking fee.
None
I have confirmed that now this example runs when payment address is funded with 10 ada. I also confirmed that error is thrown if there isn't at least 2.5 ada to cover staking registration and transaction fee.

delegate-stake-example to consider 2 ada stake key registration fee

---

test/check/workflows/delegation.ros

This PR improves delegation workflow to make it easier to use.
1. More logs were added using `print_message`
2. The amount to be received has been reduced to `10 ADA`
3. It properly works if `10 ADA` or more are received in the address
n/a
As described [here](https://github.com/input-output-hk/cardano-rosetta/tree/master/test/check#delegation-workflow)

refactor: improved logging and mounts in delegation workflow

---

test/check/workflows/transfer.ros

Improved transfer workflow
1. The amount to be received has been reduced to 10 ADA
2. It properly works if 10 ADA or more are received in the address
n/a
As described [here](https://github.com/input-output-hk/cardano-rosetta/tree/master/test/check#delegation-workflow)

refactor: improved transfer workflow with proper funds limits

---

.github/workflows/ci.yml
cardano-rosetta-server/README.md
cardano-rosetta-server/test/e2e/account/account-api.test.ts
cardano-rosetta-server/test/e2e/block/block-api.test.ts
cardano-rosetta-server/test/e2e/block/block-transactions-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-combine-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-derive-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-hash-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-metadata-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-parse-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-submit-api.test.ts
cardano-rosetta-server/test/e2e/jest-setup/docker.ts
cardano-rosetta-server/test/e2e/jest-setup/jest-setup.ts
cardano-rosetta-server/test/e2e/network/netowork-status-api.test.ts
cardano-rosetta-server/test/e2e/network/network-list-api.test.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
cardano-rosetta-server/test/e2e/server/server.test.ts
cardano-rosetta-server/test/e2e/utils/test-utils.ts

This PR allows setting different db snapshots to run e2e tests
A separate snapshot is loaded on a different db. Then each test can define which db is it willing to use.
- Snapshots were renamed
- Default e2e test db will be named `mainnet`
1. Previous tests need to run
2. You can add the following sample test and check it's querying the launchpad snapshot:
```typescript
test('Launchpad', async () => {
const launchpad = setupDatabase(process.env.DB_CONNECTION_STRING, 'launchpad');
const launchpadServer = setupServer(launchpad);
const response = await launchpadServer.inject({
method: 'post',
url: '/block',
payload: generatePayload(1)
});
expect(response.statusCode).toEqual(StatusCodes.OK);
expect(response.json().block.block_identifier.hash).toEqual("da5cfaff39fde97c797cf5a6c3657d10b603cea1da …
```

Use test data from launchpad

---

cardano-rosetta-server/src/server/openApi.json
cardano-rosetta-server/src/types/rosetta-types.d.ts

After reviewing `serialization-lib` multiassets impl I relized MA mapping wasn't properly done in #278 
- `TransactionOutput` contains, in it's metadata an array of `MultiAssets` (aka token bundle)
- Each `MultiAsset` contains he `policyId` and the list of assets it contains.
API changed thi affecting #268 
n/a

fix: multiassets schema wasn't properly mapped

---

cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts

Adds token asset value validation. It must be a positive number for output operations.
Also adds some logging calls.
Resolves #294

fix: validate asset values are positive number for output operations

---

docs/multi-assets-support.md
docs/rosetta-custom-definitions.md
examples/README.md
examples/commons.ts
examples/ma-transfer-example.ts
examples/package.json

Adds a TypeScript script for sending a transaction with multi assets at `examples/` and also updates the documentation for multi assets implementation.
Closes #275.

Add example for tx with ma operations and update docs for multi assets implementation

---

cardano-rosetta-server/src/server/utils/validations.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts

Adds validations to check token symbol and policy to be a hex string and the corresponding automated tests.
Closes #299

feat: validate token policy and symbol to be a hex string

---

cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts

Given that asset names would contain special characters, using localeCompare can behave in unexpected ways since current locale is used to perform that.
Use JS native support for binary strings like it is explained in this [Rosetta Code Wiki].(https://rosettacode.org/wiki/Binary_strings#JavaScript)

fix: use binary string comparator instead of locale comparator

---

cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts

Tests for invalid non-hex string multi assets policy weren't being done ok because they didn't satisfy the policy length validation.
Run server tests.

test: fix test for invalid non hex ma policy

---

cardano-rosetta-server/src/server/utils/cardano/cli/cardanonode-cli.ts
cardano-rosetta-server/test/unit/utils/cardano/cli/cardanonode-cli.test.ts

This PR allows sending transactions to both Shelley and Mary
Based on a discussion with @rhyslbw there isn't a clean way detect which era is the node running using the `cardano-cli` and, therefore, to update the tx encoding to be sent to it when submitting a transactions. That being said, it was defined to try different eras and fall-back to different ones if a `DecoderErrorDeserialiseFailure` error is found.
Transaction sending is affected by this change
- Testing this PR is quite complex as it's required to have a way to this this with different eras. We executed this on a `mary` network and then changed the container (edited the file and then restarted) to specify shelley as default one making the fall back to happen all the time.
- All the test cases have been automated although the …

feat: try multiple eras when sending a transaction

---

config/ecosystem.config.js

Logs are currently being persisted in the container, which is not ideal since it's best to delegate log management outside of the container via the Docker log driver interface.
Disable the PM2 log persistence.

chore: disable log persistence

---

cardano-rosetta-server/src/server/controllers/account-controller.ts
cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
cardano-rosetta-server/src/server/models.ts
cardano-rosetta-server/src/server/services/block-service.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/test/unit/utils/data-mapper.test.ts

Improves a hard to follow algorithm done at the moment of multi assets implementation for `account/balance` response.
In order to reduce the algorithm logic when mapping utxo data,  a query for multi assets balances was added. Besides that, some part of the algorithm's complexity is left since it's needed for `coins` object.
Closes #288.

refactor: refact multi assets data mapper

---

cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/services/cardano-services.ts
cardano-rosetta-server/src/server/utils/cardano/addresses.ts
cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts
cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts
cardano-rosetta-server/src/server/utils/constants.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/test/e2e/construction/construction-derive-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts
cardano-rosetta-server/test/e2e/environment-parser.test.ts
cardano-rosetta-server/test/e2e/utils/test-utils.ts
cardano-rosetta-server/test/unit/utils/cardano/cli/cardanonode-cli.test.ts

This PR removes linter warnings.
- Disable unneeded rules for sepecific lines (most of them because some validations where already made before those lines and the rules were redundant).
- Add missing return types to functions.
- Refactor `getAddressPrefix` function to make it more general for both staking and non staking addresses.

refactor: linter warning fixes

---

cardano-rosetta-server/.eslintrc
cardano-rosetta-server/src/server/utils/cardano/operations-processor.ts
cardano-rosetta-server/src/server/utils/errors.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
cardano-rosetta-server/test/e2e/utils/test-utils.ts

The `/construction/payloads` endpoint now returns a more specific error when an invalid pool key hash is provided for a stake delegation operation.
New function implemented with the already existing validation for no pool key hash provided and with the new one if the format is not valid.
New error type was introduced and the numbers of others have been adapted.
New e2e test has been added to assert this error and it is run as usual with the rest.
This improves the error message that appears in the scenario mentioned in issue #286

feat(payloads): invalid pool key hash error handling

---

cardano-rosetta-server/README.md
cardano-rosetta-server/config/exemptions.json
cardano-rosetta-server/src/server/controllers/account-controller.ts
cardano-rosetta-server/src/server/controllers/construction-controller.ts
cardano-rosetta-server/src/server/controllers/network-controller.ts
cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
cardano-rosetta-server/src/server/models.ts
cardano-rosetta-server/src/server/openApi.json
cardano-rosetta-server/src/server/services/block-service.ts
cardano-rosetta-server/src/server/services/cardano-services.ts
cardano-rosetta-server/src/server/services/network-service.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/src/server/utils/errors.ts
cardano-rosetta-server/src/server/utils/validations.ts
cardano-rosetta-server/src/types/app.d.ts
cardano-rosetta-server/src/types/rosetta-types.d.ts
cardano-rosetta-server/test/e2e/account/account-api.test.ts
cardano-rosetta-server/test/e2e/account/account-balance-api.test.ts
cardano-rosetta-server/test/e2e/account/account-coins-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-derive-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-parse-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
cardano-rosetta-server/test/unit/utils/data-mapper.test.ts

Updates api to 1.4.10
- updates `openApi.json` according to Rosetta 1.4.10
- `/account/coins` endpoint added
- `/account/balance` adapted
- deprecate address based fields at `ConstructionDeriveResponse`, `ConstructionParseResponse` and `SigningPayload`
- Support Account Balance Tracking "Exemptions"
- Update network options response (adds  `historical_balance_lookup` and `mempool_coins` fields at NetworkOptionsResponse.Allow)
Running the test suits should be enough. Old tests were adapted and new ones were created for `/account/coins`.
Closes #335.

Upgrade to Rosetta 1.4.10

---

cardano-rosetta-server/README.md
cardano-rosetta-server/src/server/server.ts
cardano-rosetta-server/src/types/app.d.ts

Body limit of requests can be increased by using the new env var `BODY_LIMIT`, if it is not present then default will be set which is 1048576 (1MiB)

Increment max body limit

---

cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
cardano-rosetta-server/src/server/models.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/test/e2e/block/block-transactions-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts

Adds support for pool retirements at **data api**.
A new type of operation was added called **operation retirement* in a previous branch. This branch consist in return these kind of operations in the block transaction queried.
New tests were introduced in order to cover new test cases introduced.
Closes data api issue descripted at #342

feat: pool retirement operation in block transaction endpoints

---

examples/README.md
examples/package.json
examples/pool-registration-with-cert-example.ts

Adds an example of submitting a transaction with `pool registration with cert` operation at `/examples`

feat: add pool registration with cert example and doc

---

cardano-rosetta-server/src/server/controllers/construction-controller.ts
cardano-rosetta-server/src/server/utils/errors.ts
cardano-rosetta-server/test/e2e/construction/construction-submit-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
cardano-rosetta-server/test/unit/utils/rosetta-error-mapper.test.ts

This is a fix for cardano rosetta implementation when cardano node throws OutsideValidityIntervalUTxO error and rosetta throws generic 5006 error code without any details what has happened.
Introduce logic that maps cardano-node error to a broader rosetta api error.
Add OutsideValidityIntervalUTxO error within a new 4037 code.
As stated above.
Tests were updated.

Catch OutsideValidityIntervalUTxO node error in construction controller

---

cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts

Filter invalid transaction from queries that calculate balance with the new `valid_contract` field introduced in Alonzo

feat: filter invalid txs from utxo and balance queries

---

cardano-rosetta-server/package.json
cardano-rosetta-server/src/server/controllers/network-controller.ts
cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
cardano-rosetta-server/src/server/models.ts
cardano-rosetta-server/src/server/utils/constants.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/test/e2e/account/account-balance-api.test.ts
cardano-rosetta-server/test/e2e/block/block-transactions-api.test.ts
cardano-rosetta-server/test/e2e/fixture-data.ts
cardano-rosetta-server/test/e2e/network/network-options-api.test.ts

This PR adds a new operation status for invalid transactions depending on the `valid_contract` field

feat: add invalid operation status for invalid txs

---

README.md

The documentation currently doesn't allow for seamless communication of remote vs locally built running. It's also not user-friendly for copy/paste.  
- Changes the build step to tag with the org scope to allow common run commands.
- Adds specific commands for each supported network, to facilitate copy/paste, assigning a
different port to allow parallel running.
- Non-breaking since mainnet volume is the same.
- Chicken-before-egg situation here in an attempt to expedite the process, so please replace the currently unreleased version with `master` in tests.

docs: improve docs to cover Docker Hub repository

---

cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts

Fixes a bug on `construction/parse` where inputs weren't correctly parsed and other operations data were being returned instead. In order to replicate this bug a transaction with 1 output, 1 input and 1 vote registration can be created and then parsed using the mentioned endpoint.

Fix parsed inputs on /construction/parse

---

Dockerfile
README.md
scripts/entrypoint.sh
scripts/maybe_download_cardano-db-sync_snapshot.sh

Users need the ability to utilise the supplied cardano-db-sync snapshots, to expedite the PostgreSQL sync which would otherwise take many hours. As there is no snapshot of the cardano-node state, the restoration should only proceed if the instance contains some state in the expected directory, otherwise cardano-db-sync will roll back to the node’s tip, or genesis in the case of a new instance, and thus eliminate most benefits of the feature. 
Introduces a build argument to download and store the provided remote snapshot
in the image, plus startup logic to restore unless it's the first run with no `cardano-node` state.
At least 3 scenarios should be tested:
1. Instance fully synced, observe no lengthy sync
2. Instance partially synced, observe a proportional sync
3. New instance, observe …

feat: cardano-db-sync snapshot restoration

---

cardano-rosetta-server/src/server/controllers/construction-controller.ts
cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts
cardano-rosetta-server/src/server/index.ts
cardano-rosetta-server/src/server/services/cardano-services.ts
cardano-rosetta-server/src/server/services/services.ts
cardano-rosetta-server/src/server/utils/data-mapper.ts
cardano-rosetta-server/src/server/utils/index-mapper.ts
cardano-rosetta-server/src/types/rosetta-types.d.ts
cardano-rosetta-server/test/e2e/account/account-balance-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
cardano-rosetta-server/test/e2e/construction/construction-preprocess-api.test.ts
cardano-rosetta-server/test/e2e/utils/test-utils.ts
cardano-rosetta-server/test/unit/services/cardano-services.test.ts

The current implementation uses the genesis file for fee and deposit parameters, which works for now since those values have not been updated, but the epoch_param table contains the active values based on the epoch and should be used instead. 
Add new method to query for Deposit Parameters at `BlockchainRepository`.
Replace `BlockchainRepository` per `DepositParameters` in  `CardanoService` dependencies in order to query deposit parameters dinamically

Replace genesis protocol param references to epoch_param table

---

cardano-rosetta-server/src/server/db/blockchain-repository.ts
cardano-rosetta-server/src/server/utils/cardano/addresses.ts
cardano-rosetta-server/src/server/utils/cardano/transactions-processor.ts
cardano-rosetta-server/src/server/utils/validations.ts
cardano-rosetta-server/test/unit/utils/cardano/addresses.test.ts
cardano-rosetta-server/test/unit/utils/validations.test.ts

Improve metadata handling for vote registration labels. There was a missig check that made cases such as https://testnet.cardanoscan.io/transaction/c9ad03f41fd36996a8b8588ee21fd95acb0f4e784a554724f0776306f8358042 to get into an error due to invalid expected format
Add validation for metadata vote registration fields. Check for fields to be hex strings
N/A

fix: validate type of  metadata field for vote registrations

---

Dockerfile
cardano-rosetta-server/docker-compose.yml
test/check/configuration/data/vasil-qa_sample.json

Bumps Cardano Node and Cardano Db Sync to latest versions.
Also, updates deprecated configuration file to run check:data script for `vasil-dev/vasil-qa` network

Cardano Node 1.35.0 and Cardano Db Sync 13.0.0

---

cardano-rosetta-server/src/server/db/queries/search-transactions-queries.ts
cardano-rosetta-server/test/e2e/fixture-data.ts
cardano-rosetta-server/test/e2e/search/search-transactions-api.test.ts

Fixes a bug at `/search/transaction`, where it didn't return transactions where the coin was spent, making `coin` and `address` filters work incorrectly.
Closes #454

fix(searchTransactions): fix on search by addresses and coins

---

nix/sources.json
nix/sources.nix

Fixes the nix build by updating iohk-nix from which the nodejs version is selected.
Also updates niv's `sources.nix`.
`nix build .#hydraJobs.x86_64-linux.required`

Update iohk-nix and niv

---

cardano-rosetta-server/src/server/controllers/construction-controller.ts
cardano-rosetta-server/src/server/openApi.json
cardano-rosetta-server/src/types/rosetta-types.d.ts
cardano-rosetta-server/test/e2e/construction/construction-metadata-api.test.ts

_A clear and concise description of what this pull request does or fixes._
A recent [commit](https://github.com/input-output-hk/cardano-rosetta/commit/ec56d250c2a231991dc2ad83221875c2ab47304d#diff-3e4a5ae0c3ef451b5fb71feaff4ae449d048c43a4943baf5b34ce18ce627fd16R186) introduced a bug where the response of `/construction/metadata` endpoint will respond with `protocol_parameter` outside the `metadata` object. This breaks the rosetta [spec](https://www.rosetta-api.org/docs/models/ConstructionMetadataResponse.html) and also in the subsequent `/construction/payloads` call, it is read from `req.body.metadata.protocol_parameter` which will return null.
This fix moves the `protocol_parameter` in the `metadata`
_**Optional** Explain how does this PR solves the problem stated in …

fix: nest protocol params inside metadata object of construction endpoint

---

Dockerfile
README.md

#523 added support for multi-platform builds, which broke in #527 when refactoring away from using `cabal install`, however, as we currently do not have the cross-platform build pipeline in CI, it was merged undetected. We've also been based on Ubuntu 20.04, so this was a good opportunity to move to the later LTS, plus the latest pinned commit in the IOG fork of libsodium.
See commits.
We need to observe successful native builds and smoke tests on each supported architecture. CI will handle the x86 build but not ARM.

Build/fix multi platform support + Ubuntu 22.04 upgrade
